apiVersion: apps/v1
kind: Deployment
metadata: 
      name: todoapp
      labels:
        app: todoapp
spec: 
    replicas: 1
    strategy: 
        type: RollingUpdate
    template:
          metadata: 
                name: todoapp 
                labels:
                      app: todoapp          
          spec: 
             containers: 
                  - name: todo-container
                    image: aamantamboli/todoapp:latest
                    resources: 
                      requests:
                        cpu: "25m"
                        memory: "50Mi"
                      limits:
                        cpu: "50m"
                        memory: "100Mi"
                    ports:
                      - name: http
                        containerPort: 80
                        protocol: TCP                      
    selector:
       matchLabels:
           app: todoapp   
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata: 
   name: autoscalingpod1
   labels:
     app: autoscalingpod1
spec:
  scaleTargetRef:
     apiVersion: apps/v1
     kind: Deployment 
     name: todoapp  
  minReplicas: 1
  maxReplicas: 2
  metrics:
     - type: Resource
       resource:
           name: cpu
           target:
             type: Utilization
             averageUtilization: 50
